### ISSUE TITLE
DEPRECATION: Addon files were detected ... , but no JavaScript preprocessors were found for `ember-cli-deploy-s3-pack`

### ISSUE THREAD

**Issue by psteininger** [Gaurav0/ember-cli-deploy-s3-pack#11]
This deprecation message shows up when running `ember s`:
DEPRECATION: Addon files were detected ... , but no JavaScript preprocessors were found for `ember-cli-deploy-s3-pack`.
Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-cli-deploy-s3-pack`'s `package.json`.

**Comment by Gaurav0** [comment]
Are you running `ember s` directly on ember-cli-deploy-s3-pack or a host application?

**Comment by psteininger** [comment]
@Gaurav0 I am running it on my app, which uses `ember-cli-deploy-s3-pack`.

**Comment by psteininger** [comment]
I think moving `ember-cli-babel` from `devDependencies` to `dependencies` will do the trick. It is something I have noticed since Ember cli 3.0.0

**Comment by Gaurav0** [comment]
Thanks! Would you like to make a PR?

**Comment by psteininger** [comment]
Let me try @Gaurav0

**Comment by psteininger** [comment]
@Gaurav0 PR complete. tested locally, the deprecation is gone.
